import Head from 'next/head';
import styles from './Layout.module.css';
import Header from './Header/Header';
import Sidebar from './Sidebar/Sidebar';
import Footer from './Footer/Footer';
const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>zkEase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/favicon.ico" />
      </Head>
      <div className={styles.wrapper}>
        <Header className={styles.header} />
        <Sidebar className={styles.sidebar} />
        <div className={styles.main}>{children}</div>
        <Footer className={styles.footer} />
      </div>
    </>
  );
};

export default Layout;
